version: "3.8"
services:
  expresscash-frontend:
    container_name: expresscash-frontend
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - expresscash_network

networks:
  expresscash_network:
